### ISSUE TITLE
Sdk.Docs is not installed in flapjack setup

### ISSUE THREAD

**Issue by csoriano1618** [endlessm/flapjack#15]
Got this error after flatpjack setup + flapjack build:

[csoriano@ibm-p8-kvm-03-guest-02 flapjack]$ flapjack build
Emptying app dir '/home/csoriano/flapjack/runtime-build'
Downloading sources
Initializing build dir
error: Requested extension org.gnome.Sdk.Docs not installed
Error: Child process exited with code 1

**Comment by ptomato** [comment]
Thanks for the report! I wanted to fix this quickly, since it affects the first experience with flapjack, but I didn't get around to it today.

Are you using a `flapjack.ini` config file, specifically one with the `add_extensions` key? Or just the default configuration to build org.gnome.Sdk?

**Comment by csoriano1618** [comment]
default config

**Comment by ptomato** [comment]
Check #16 and see if it works for you?

**Comment by ptomato** [comment]
@csoriano1618 did you get a chance to check if the patch fixes your problem?
