### ISSUE TITLE
Video missing

### ISSUE THREAD

**Issue by ferdnyc** [endlessm/flapjack#30]
Alas, YouTube reports that whatever video is linked to from "[well-known trick of running GEdit with all the labels upside-down](http://www.youtube.com/watch?v=70Kl9ft5DGA&t=40m4s)" in the Readme file "isn't available anymore".

**Comment by ptomato** [comment]
Might have been [this video](https://www.youtube.com/watch?v=hE5nJrGnX-U)

**Comment by ferdnyc** [comment]
@ptomato That looks correct, and even the time index matches up. Thanks!
